// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxXRSkgo5LCSKDuXAi0uMCHodRfulos8',
    appId: '1:325417468624:web:c44a4e197a5ecc3652d4d5',
    messagingSenderId: '325417468624',
    projectId: 'streaming-app-test-cf57b',
    authDomain: 'streaming-app-test-cf57b.firebaseapp.com',
    storageBucket: 'streaming-app-test-cf57b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47VvX4Sjq-8tWJJxhpAfgibmnMHT1JRY',
    appId: '1:325417468624:android:e17a79d226b8eb0752d4d5',
    messagingSenderId: '325417468624',
    projectId: 'streaming-app-test-cf57b',
    storageBucket: 'streaming-app-test-cf57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH8FIjBPQ2ITibEHQxK6g_ssHsXeC5lZM',
    appId: '1:325417468624:ios:01d537df90de162752d4d5',
    messagingSenderId: '325417468624',
    projectId: 'streaming-app-test-cf57b',
    storageBucket: 'streaming-app-test-cf57b.appspot.com',
    iosClientId: '325417468624-ishu8r8dv0b4etjmu0pbgdmlfe6em8uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH8FIjBPQ2ITibEHQxK6g_ssHsXeC5lZM',
    appId: '1:325417468624:ios:01d537df90de162752d4d5',
    messagingSenderId: '325417468624',
    projectId: 'streaming-app-test-cf57b',
    storageBucket: 'streaming-app-test-cf57b.appspot.com',
    iosClientId: '325417468624-ishu8r8dv0b4etjmu0pbgdmlfe6em8uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamingApp',
  );
}
